<?php

declare(strict_types=1);

/**
 * @file
 * Provides an advertisement entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function advertisement_theme(): array {
  return [
    'advertisement' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for advertisement templates.
 *
 * Default template: advertisement.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the advertisement information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_advertisement(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function advertisement_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish advertisements.
      $storage = \Drupal::entityTypeManager()->getStorage('advertisement');
      $advertisement_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($advertisement_ids) as $advertisement) {
        $advertisement->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize advertisements.
      $storage = \Drupal::entityTypeManager()->getStorage('advertisement');
      $advertisement_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($advertisement_ids) as $advertisement) {
        $advertisement->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function advertisement_user_predelete(UserInterface $account): void {
  // Delete advertisements that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('advertisement');
  $advertisement_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($advertisement_ids)
  );
}
